source 'https://rubygems.org'

gem 'dashing'
gem 'elastic-beanstalk'

## Remove this if you don't need a twitter widget.
gem 'bundler'
gem 'twitter', '>= 5.9.0'
gem 'forecast_io'
gem 'mysql2'
gem 'rest-client'
gem 'json'
gem 'puma'
gem 'httparty'
gem 'rack', '~> 1.5.4'
gem 'xml-simple'
gem 'nokogiri'
gem 'google-api-client'
gem 'hipchat'
gem 'prawn'
gem 'logger'
gem 'activesupport'
gem 'mail'
gem 'puma_worker_killer'
