source 'https://rubygems.org'

ruby '2.2.5'
gem 'dashing'

## Remove this if you don't need a twitter widget.
gem 'bundler'
gem 'twitter', '>= 5.9.0'
gem 'forecast_io'
gem 'mysql2'
gem 'rest-client'
gem 'json'
gem 'puma'
gem 'httparty'
gem 'rack', '~> 1.5.4'
gem 'figaro', :git => 'https://github.com/bpaquet/figaro.git', :branch => 'sinatra'
gem 'xml-simple'
gem 'nokogiri'
gem 'google-api-client'
gem 'redis'
gem 'hipchat'
